In [1]:
pwd

'/Users/smiyengi/Documents/UNIVERSITY OF OREGON BOOTCAMP/module_4/module_4_challenge/PyCitySchools/Starter_Code/PyCitySchools/Resources'

In [2]:
import pandas as pd

school_data ="./schools_complete.csv"
student_data = "./students_complete.csv"

schooldata_df = pd.read_csv(school_data)
studentdata_df = pd.read_csv(student_data)

# merge the dataframes
combined_complete = pd.merge(studentdata_df, schooldata_df, how="left", on="school_name")

combined_complete.count()

Student ID       39170
student_name     39170
gender           39170
grade            39170
school_name      39170
reading_score    39170
math_score       39170
School ID        39170
type             39170
size             39170
budget           39170
dtype: int64

## District Summary

## Unique Schools

In [3]:
len(schooldata_df)

15

## Total Students

In [4]:
len(studentdata_df)

39170

## Total Budget

In [5]:
schooldata_df["budget"].sum()

24649428

## Average Math Score

In [6]:
studentdata_df['math_score'].mean()

78.98537145774827

## Average Reading Score

In [7]:
studentdata_df['reading_score'].mean()

81.87784018381414

## Percentage of students who passed math

In [8]:
(studentdata_df['math_score'] >= 70).mean() * 100

74.9808526933878

## Percentage of students who passed reading

In [9]:
(studentdata_df['reading_score'] >= 70).mean() * 100

85.80546336482001

## Percentage of students who passed math and reading

In [10]:
((studentdata_df['reading_score'] >= 70) & (studentdata_df['math_score'] >= 70)).mean() * 100

65.17232575950983

In [11]:
# Summary for output

unique_schools = len(combined_complete["school_name"].unique())
total_students = len(combined_complete ["Student ID"].unique())
total_budget = schooldata_df["budget"].sum()
average_math = combined_complete["math_score"].mean()
average_reading = combined_complete["reading_score"].mean()
perc_pass_math = (studentdata_df['math_score'] >= 70).mean() * 100
perc_pass_reading = (studentdata_df['reading_score'] >= 70).mean() * 100
perc_pass_both = ((studentdata_df['reading_score'] >= 70) & (studentdata_df['math_score'] >= 70)).mean() * 100

district_summary = pd.DataFrame(
    {
        "Total Schools": [unique_schools],
        "Total Students": [total_students],
        "Total Budget": [total_budget],
        "Average Math Score": [average_math],
        "Average Reading Score": [average_reading],
        "% Passing Math": [perc_pass_math],
        "% Passing Reading": [perc_pass_reading],
        "% Overall Passing": [perc_pass_both]
    }
)

#Format

district_summary["Total Students"] = district_summary["Total Students"].map("{:,}".format)
district_summary["Total Budget"] = district_summary["Total Budget"].map("${:,.2f}".format)
district_summary

,Total Schools,Total Students,Total Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
0,15,"39,170","$24,649,428.00",78.985371,81.87784,74.980853,85.805463,65.172326

## School Summary

## Per student budget | Average math score | Average reading score

In [12]:

school_summary_df = schooldata_df.copy()
school_summary_df['per_student_budget'] =  (schooldata_df['budget'] / schooldata_df['size']).map("${:,.2f}".format)
reading_score_df = studentdata_df.groupby(by='school_name')['reading_score'].mean(numeric_only=True)
math_score_df = studentdata_df.groupby(by='school_name')['math_score'].mean(numeric_only=True)
school_summary_df = pd.merge(left=school_summary_df, right=reading_score_df, on='school_name', how='left', )
del(reading_score_df)
school_summary_df = pd.merge(left=school_summary_df, right=math_score_df, on='school_name', how='left')
del(math_score_df)
school_summary_df.rename(columns={'reading_score': 'reading_score_avg', 'math_score': 'math_score_avg'}, inplace=True)
school_summary_df['budget'] = school_summary_df['budget'].map("${:,.2f}".format)
school_summary_df['size'] = school_summary_df['size'].map("{:,}".format)
school_summary_df

,School ID,school_name,type,size,budget,per_student_budget,reading_score_avg,math_score_avg
0,0,Huang High School,District,"2,917","$1,910,635.00",$655.00,81.182722,76.629414
1,1,Figueroa High School,District,"2,949","$1,884,411.00",$639.00,81.158020,76.711767
2,2,Shelton High School,Charter,"1,761","$1,056,600.00",$600.00,83.725724,83.359455
3,3,Hernandez High School,District,"4,635","$3,022,020.00",$652.00,80.934412,77.289752
4,4,Griffin High School,Charter,"1,468","$917,500.00",$625.00,83.816757,83.351499
5,5,Wilson High School,Charter,"2,283","$1,319,574.00",$578.00,83.989488,83.274201
6,6,Cabrera High School,Charter,"1,858","$1,081,356.00",$582.00,83.975780,83.061895
7,7,Bailey High School,District,"4,976","$3,124,928.00",$628.00,81.033963,77.048432
8,8,Holden High School,Charter,427,"$248,087.00",$581.00,83.814988,83.803279
9,9,Pena High School,Charter,962,"$585,858.00",$609.00,84.044699,83.839917
10,10,Wright High School,Charter,"1,800","$1,049,400.00",$583.00,83.955000,83.682222
11,11,Rodriguez High School,District,"3,999","$2,547,363.00",$637.00,80.744686,76.842711
12,12,Johnson High School,District,"4,761","$3,094,650.00",$650.00,80.966394,77.072464
13,13,Ford High School,District,"2,739","$1,763,916.00",$644.00,80.746258,77.102592
14,14,Thomas High School,Charter,"1,635","$1,043,130.00",$638.00,83.848930,83.418349

## % passing math (the percentage of students who passed math) | % passing reading (the percentage of students who passed reading)

In [13]:
def agg_pass_mark(x):
  '''
  function to aggregate the percentage passing the subject.
  '''
  pass_mark = 70
  return (x >= pass_mark).mean() * 100

In [14]:
pass_math_df = studentdata_df.groupby('school_name', group_keys=False)['math_score'].agg(agg_pass_mark)
school_summary_df = pd.merge(left=school_summary_df, right=pass_math_df, on='school_name', how='left')
pass_reading_df = studentdata_df.groupby('school_name', group_keys=False)['reading_score'].agg(agg_pass_mark)
school_summary_df = pd.merge(left=school_summary_df, right=pass_reading_df, on='school_name', how='left')
school_summary_df.rename(columns={'reading_score': r'% pass_reading', 'math_score': r'% pass_math'}, inplace=True)
school_summary_df

,School ID,school_name,type,size,budget,per_student_budget,reading_score_avg,math_score_avg,% pass_math,% pass_reading
0,0,Huang High School,District,"2,917","$1,910,635.00",$655.00,81.182722,76.629414,65.683922,81.316421
1,1,Figueroa High School,District,"2,949","$1,884,411.00",$639.00,81.158020,76.711767,65.988471,80.739234
2,2,Shelton High School,Charter,"1,761","$1,056,600.00",$600.00,83.725724,83.359455,93.867121,95.854628
3,3,Hernandez High School,District,"4,635","$3,022,020.00",$652.00,80.934412,77.289752,66.752967,80.862999
4,4,Griffin High School,Charter,"1,468","$917,500.00",$625.00,83.816757,83.351499,93.392371,97.138965
5,5,Wilson High School,Charter,"2,283","$1,319,574.00",$578.00,83.989488,83.274201,93.867718,96.539641
6,6,Cabrera High School,Charter,"1,858","$1,081,356.00",$582.00,83.975780,83.061895,94.133477,97.039828
7,7,Bailey High School,District,"4,976","$3,124,928.00",$628.00,81.033963,77.048432,66.680064,81.933280
8,8,Holden High School,Charter,427,"$248,087.00",$581.00,83.814988,83.803279,92.505855,96.252927
9,9,Pena High School,Charter,962,"$585,858.00",$609.00,84.044699,83.839917,94.594595,95.945946
10,10,Wright High School,Charter,"1,800","$1,049,400.00",$583.00,83.955000,83.682222,93.333333,96.611111
11,11,Rodriguez High School,District,"3,999","$2,547,363.00",$637.00,80.744686,76.842711,66.366592,80.220055
12,12,Johnson High School,District,"4,761","$3,094,650.00",$650.00,80.966394,77.072464,66.057551,81.222432
13,13,Ford High School,District,"2,739","$1,763,916.00",$644.00,80.746258,77.102592,68.309602,79.299014
14,14,Thomas High School,Charter,"1,635","$1,043,130.00",$638.00,83.848930,83.418349,93.272171,97.308869

## % overall passing (the percentage of students who passed math AND reading

In [15]:
def agg_function_pass_both(x):
  pass_mark = 70
  a = (x['reading_score'] >= pass_mark) & (x['math_score'] >= pass_mark)
  return a.mean() * 100

In [16]:
students_passing_df = studentdata_df.groupby('school_name',).apply(agg_function_pass_both)
school_summary_df = pd.merge(left=school_summary_df, right=students_passing_df.to_frame(), on='school_name', how='left')
del(students_passing_df)
school_summary_df.rename(columns={0: r'% overall passing'}, inplace=True)
school_summary_df

,School ID,school_name,type,size,budget,per_student_budget,reading_score_avg,math_score_avg,% pass_math,% pass_reading,% overall passing
0,0,Huang High School,District,"2,917","$1,910,635.00",$655.00,81.182722,76.629414,65.683922,81.316421,53.513884
1,1,Figueroa High School,District,"2,949","$1,884,411.00",$639.00,81.158020,76.711767,65.988471,80.739234,53.204476
2,2,Shelton High School,Charter,"1,761","$1,056,600.00",$600.00,83.725724,83.359455,93.867121,95.854628,89.892107
3,3,Hernandez High School,District,"4,635","$3,022,020.00",$652.00,80.934412,77.289752,66.752967,80.862999,53.527508
4,4,Griffin High School,Charter,"1,468","$917,500.00",$625.00,83.816757,83.351499,93.392371,97.138965,90.599455
5,5,Wilson High School,Charter,"2,283","$1,319,574.00",$578.00,83.989488,83.274201,93.867718,96.539641,90.582567
6,6,Cabrera High School,Charter,"1,858","$1,081,356.00",$582.00,83.975780,83.061895,94.133477,97.039828,91.334769
7,7,Bailey High School,District,"4,976","$3,124,928.00",$628.00,81.033963,77.048432,66.680064,81.933280,54.642283
8,8,Holden High School,Charter,427,"$248,087.00",$581.00,83.814988,83.803279,92.505855,96.252927,89.227166
9,9,Pena High School,Charter,962,"$585,858.00",$609.00,84.044699,83.839917,94.594595,95.945946,90.540541
10,10,Wright High School,Charter,"1,800","$1,049,400.00",$583.00,83.955000,83.682222,93.333333,96.611111,90.333333
11,11,Rodriguez High School,District,"3,999","$2,547,363.00",$637.00,80.744686,76.842711,66.366592,80.220055,52.988247
12,12,Johnson High School,District,"4,761","$3,094,650.00",$650.00,80.966394,77.072464,66.057551,81.222432,53.539172
13,13,Ford High School,District,"2,739","$1,763,916.00",$644.00,80.746258,77.102592,68.309602,79.299014,54.289887
14,14,Thomas High School,Charter,"1,635","$1,043,130.00",$638.00,83.848930,83.418349,93.272171,97.308869,90.948012

## Highest Performing School (by % overall passing)

In [17]:
top_schools = school_summary_df.sort_values(by=r'% overall passing', ascending=False)
top_schools.head(n=5)

,School ID,school_name,type,size,budget,per_student_budget,reading_score_avg,math_score_avg,% pass_math,% pass_reading,% overall passing
6,6,Cabrera High School,Charter,"1,858","$1,081,356.00",$582.00,83.975780,83.061895,94.133477,97.039828,91.334769
14,14,Thomas High School,Charter,"1,635","$1,043,130.00",$638.00,83.848930,83.418349,93.272171,97.308869,90.948012
4,4,Griffin High School,Charter,"1,468","$917,500.00",$625.00,83.816757,83.351499,93.392371,97.138965,90.599455
5,5,Wilson High School,Charter,"2,283","$1,319,574.00",$578.00,83.989488,83.274201,93.867718,96.539641,90.582567
9,9,Pena High School,Charter,962,"$585,858.00",$609.00,84.044699,83.839917,94.594595,95.945946,90.540541

## Lowest Performing Schools (by % overall passing)

In [18]:
bottom_schools = school_summary_df.sort_values(by=r'% overall passing', ascending=True)
bottom_schools.head(n=5)

,School ID,school_name,type,size,budget,per_student_budget,reading_score_avg,math_score_avg,% pass_math,% pass_reading,% overall passing
11,11,Rodriguez High School,District,"3,999","$2,547,363.00",$637.00,80.744686,76.842711,66.366592,80.220055,52.988247
1,1,Figueroa High School,District,"2,949","$1,884,411.00",$639.00,81.158020,76.711767,65.988471,80.739234,53.204476
0,0,Huang High School,District,"2,917","$1,910,635.00",$655.00,81.182722,76.629414,65.683922,81.316421,53.513884
3,3,Hernandez High School,District,"4,635","$3,022,020.00",$652.00,80.934412,77.289752,66.752967,80.862999,53.527508
12,12,Johnson High School,District,"4,761","$3,094,650.00",$650.00,80.966394,77.072464,66.057551,81.222432,53.539172

## Math Scores by Grade

In [19]:
# Use the code provided to separate the data by grade
ninth_graders = studentdata_df[(studentdata_df["grade"] == "9th")]
tenth_graders = studentdata_df[(studentdata_df["grade"] == "10th")]
eleventh_graders = studentdata_df[(studentdata_df["grade"] == "11th")]
twelfth_graders = studentdata_df[(studentdata_df["grade"] == "12th")]

# Group by `school_name` and take the mean of the `math_score` column for each.
ninth_grade_math_scores = ninth_graders.groupby(by=['school_name',])['math_score'].mean(numeric_only=True).rename('9th')
tenth_grader_math_scores = tenth_graders.groupby(by=['school_name',])['math_score'].mean(numeric_only=True).rename('10th')
eleventh_grader_math_scores = eleventh_graders.groupby(by=['school_name',])['math_score'].mean(numeric_only=True).rename('11th')
twelfth_grader_math_scores = twelfth_graders.groupby(by=['school_name',])['math_score'].mean(numeric_only=True).rename('12th')

math_scores_by_grade = pd.concat([ninth_grade_math_scores, tenth_grader_math_scores, eleventh_grader_math_scores, twelfth_grader_math_scores], axis=1)
math_scores_by_grade.index.name = None
math_scores_by_grade

                             9th       10th       11th       12th
Bailey High School     77.083676  76.996772  77.515588  76.492218
Cabrera High School    83.094697  83.154506  82.765560  83.277487
Figueroa High School   76.403037  76.539974  76.884344  77.151369
Ford High School       77.361345  77.672316  76.918058  76.179963
Griffin High School    82.044010  84.229064  83.842105  83.356164
Hernandez High School  77.438495  77.337408  77.136029  77.186567
Holden High School     83.787402  83.429825  85.000000  82.855422
Huang High School      77.027251  75.908735  76.446602  77.225641
Johnson High School    77.187857  76.691117  77.491653  76.863248
Pena High School       83.625455  83.372000  84.328125  84.121547
Rodriguez High School  76.859966  76.612500  76.395626  77.690748
Shelton High School    83.420755  82.917411  83.383495  83.778976
Thomas High School     83.590022  83.087886  83.498795  83.497041
Wilson High School     83.085578  83.724422  83.195326  83.035794
Wright High School     83.264706  84.010288  83.836782  83.644986

## Reading Scores by Grade

In [20]:
# Group by `school_name` and take the mean of the `reading_score` column for each.
ninth_grade_reading_score = ninth_graders.groupby(by=['school_name',])['reading_score'].mean(numeric_only=True).rename('9th')
tenth_grader_reading_score = tenth_graders.groupby(by=['school_name',])['reading_score'].mean(numeric_only=True).rename('10th')
eleventh_grader_reading_score = eleventh_graders.groupby(by=['school_name',])['reading_score'].mean(numeric_only=True).rename('11th')
twelfth_grader_reading_score = twelfth_graders.groupby(by=['school_name',])['reading_score'].mean(numeric_only=True).rename('12th')

reading_scores_by_grade = pd.concat([ninth_grade_reading_score, tenth_grader_reading_score, eleventh_grader_reading_score, twelfth_grader_reading_score], axis=1)
reading_scores_by_grade.index.name = None
reading_scores_by_grade

                             9th       10th       11th       12th
Bailey High School     81.303155  80.907183  80.945643  80.912451
Cabrera High School    83.676136  84.253219  83.788382  84.287958
Figueroa High School   81.198598  81.408912  80.640339  81.384863
Ford High School       80.632653  81.262712  80.403642  80.662338
Griffin High School    83.369193  83.706897  84.288089  84.013699
Hernandez High School  80.866860  80.660147  81.396140  80.857143
Holden High School     83.677165  83.324561  83.815534  84.698795
Huang High School      81.290284  81.512386  81.417476  80.305983
Johnson High School    81.260714  80.773431  80.616027  81.227564
Pena High School       83.807273  83.612000  84.335938  84.591160
Rodriguez High School  80.993127  80.629808  80.864811  80.376426
Shelton High School    84.122642  83.441964  84.373786  82.781671
Thomas High School     83.728850  84.254157  83.585542  83.831361
Wilson High School     83.939778  84.021452  83.764608  84.317673
Wright High School     83.833333  83.812757  84.156322  84.073171

## Scores by School Spending

In [21]:
# Setting up the bins
spending_bins = [0, 585, 630, 645, 680]
labels = ["<$585", "$585-630", "$630-645", "$645-680"]

In [22]:
school_summary_df['spending_bins'] = pd.cut(x= school_summary_df['per_student_budget'].str.replace(pat=r'$', repl='',regex=False).astype(float),
                                            bins=spending_bins,
                                            labels=labels)
# school_summary_df

In [23]:
spending_summary = school_summary_df.sort_values(by='per_student_budget')
spending_summary

,School ID,school_name,type,size,budget,per_student_budget,reading_score_avg,math_score_avg,% pass_math,% pass_reading,% overall passing,spending_bins
5,5,Wilson High School,Charter,"2,283","$1,319,574.00",$578.00,83.989488,83.274201,93.867718,96.539641,90.582567,<$585
8,8,Holden High School,Charter,427,"$248,087.00",$581.00,83.814988,83.803279,92.505855,96.252927,89.227166,<$585
6,6,Cabrera High School,Charter,"1,858","$1,081,356.00",$582.00,83.975780,83.061895,94.133477,97.039828,91.334769,<$585
10,10,Wright High School,Charter,"1,800","$1,049,400.00",$583.00,83.955000,83.682222,93.333333,96.611111,90.333333,<$585
2,2,Shelton High School,Charter,"1,761","$1,056,600.00",$600.00,83.725724,83.359455,93.867121,95.854628,89.892107,$585-630
9,9,Pena High School,Charter,962,"$585,858.00",$609.00,84.044699,83.839917,94.594595,95.945946,90.540541,$585-630
4,4,Griffin High School,Charter,"1,468","$917,500.00",$625.00,83.816757,83.351499,93.392371,97.138965,90.599455,$585-630
7,7,Bailey High School,District,"4,976","$3,124,928.00",$628.00,81.033963,77.048432,66.680064,81.933280,54.642283,$585-630
11,11,Rodriguez High School,District,"3,999","$2,547,363.00",$637.00,80.744686,76.842711,66.366592,80.220055,52.988247,$630-645
14,14,Thomas High School,Charter,"1,635","$1,043,130.00",$638.00,83.848930,83.418349,93.272171,97.308869,90.948012,$630-645
1,1,Figueroa High School,District,"2,949","$1,884,411.00",$639.00,81.158020,76.711767,65.988471,80.739234,53.204476,$630-645
13,13,Ford High School,District,"2,739","$1,763,916.00",$644.00,80.746258,77.102592,68.309602,79.299014,54.289887,$630-645
12,12,Johnson High School,District,"4,761","$3,094,650.00",$650.00,80.966394,77.072464,66.057551,81.222432,53.539172,$645-680
3,3,Hernandez High School,District,"4,635","$3,022,020.00",$652.00,80.934412,77.289752,66.752967,80.862999,53.527508,$645-680
0,0,Huang High School,District,"2,917","$1,910,635.00",$655.00,81.182722,76.629414,65.683922,81.316421,53.513884,$645-680

## Scores by School Size

In [24]:
size_bins = [0, 1000, 2000, 5000]
size_labels = ["Small (<1000)", "Medium (1000-2000)", "Large (2000-5000)"]

In [25]:
school_summary_df['size_bins'] = pd.cut(x=school_summary_df['size'].str.replace(pat=r',', repl='',regex=False).astype(int),
                                        bins=size_bins,
                                        labels=size_labels)

In [26]:
size_summary = school_summary_df.sort_values(by='size')
size_summary

,School ID,school_name,type,size,budget,per_student_budget,reading_score_avg,math_score_avg,% pass_math,% pass_reading,% overall passing,spending_bins,size_bins
4,4,Griffin High School,Charter,"1,468","$917,500.00",$625.00,83.816757,83.351499,93.392371,97.138965,90.599455,$585-630,Medium (1000-2000)
14,14,Thomas High School,Charter,"1,635","$1,043,130.00",$638.00,83.848930,83.418349,93.272171,97.308869,90.948012,$630-645,Medium (1000-2000)
2,2,Shelton High School,Charter,"1,761","$1,056,600.00",$600.00,83.725724,83.359455,93.867121,95.854628,89.892107,$585-630,Medium (1000-2000)
10,10,Wright High School,Charter,"1,800","$1,049,400.00",$583.00,83.955000,83.682222,93.333333,96.611111,90.333333,<$585,Medium (1000-2000)
6,6,Cabrera High School,Charter,"1,858","$1,081,356.00",$582.00,83.975780,83.061895,94.133477,97.039828,91.334769,<$585,Medium (1000-2000)
5,5,Wilson High School,Charter,"2,283","$1,319,574.00",$578.00,83.989488,83.274201,93.867718,96.539641,90.582567,<$585,Large (2000-5000)
13,13,Ford High School,District,"2,739","$1,763,916.00",$644.00,80.746258,77.102592,68.309602,79.299014,54.289887,$630-645,Large (2000-5000)
0,0,Huang High School,District,"2,917","$1,910,635.00",$655.00,81.182722,76.629414,65.683922,81.316421,53.513884,$645-680,Large (2000-5000)
1,1,Figueroa High School,District,"2,949","$1,884,411.00",$639.00,81.158020,76.711767,65.988471,80.739234,53.204476,$630-645,Large (2000-5000)
11,11,Rodriguez High School,District,"3,999","$2,547,363.00",$637.00,80.744686,76.842711,66.366592,80.220055,52.988247,$630-645,Large (2000-5000)
3,3,Hernandez High School,District,"4,635","$3,022,020.00",$652.00,80.934412,77.289752,66.752967,80.862999,53.527508,$645-680,Large (2000-5000)
12,12,Johnson High School,District,"4,761","$3,094,650.00",$650.00,80.966394,77.072464,66.057551,81.222432,53.539172,$645-680,Large (2000-5000)
7,7,Bailey High School,District,"4,976","$3,124,928.00",$628.00,81.033963,77.048432,66.680064,81.933280,54.642283,$585-630,Large (2000-5000)
8,8,Holden High School,Charter,427,"$248,087.00",$581.00,83.814988,83.803279,92.505855,96.252927,89.227166,<$585,Small (<1000)
9,9,Pena High School,Charter,962,"$585,858.00",$609.00,84.044699,83.839917,94.594595,95.945946,90.540541,$585-630,Small (<1000)

## Scores by School Type

In [27]:
# By school type
average_math_score_by_type = school_summary_df.groupby(["type"])["math_score_avg"].mean()
average_reading_score_by_type = school_summary_df.groupby(["type"])["reading_score_avg"].mean()
average_percent_passing_math_by_type = school_summary_df.groupby(["type"])["% pass_math"].mean()
average_percent_passing_reading_by_type = school_summary_df.groupby(["type"])["% pass_reading"].mean()
average_percent_overall_passing_by_type = school_summary_df.groupby(["type"])["% overall passing"].mean()

# Assemble
school_type_summary = pd.DataFrame(
    {
        "Average Math Score" : average_math_score_by_type,
        "Average Reading Score": average_reading_score_by_type,
        "% Passing Math": average_percent_passing_math_by_type,
        "% Passing Reading": average_percent_passing_reading_by_type,
        "% Overall Passing": average_percent_overall_passing_by_type
    }
)

school_type_summary

,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
type,,,,,
Charter,83.473852,83.896421,93.620830,96.586489,90.432244
District,76.956733,80.966636,66.548453,80.799062,53.672208